### ISSUE TITLE
Yeah, thanks for nothing

### ISSUE THREAD

**Issue by Vulturous** [stormrage-project/stormrage-1.12-bugtracker#231]
Just glad you didn't even bother announcing you'd take the server down and make months of work on characters naught and void...

**Comment by stormrage-project** [comment]
Hello Voraxis,

we announced the reboot of Stormrage Project two months before the take down, on the old website and the forum. We are sorry, that you went inactive in the beginning of 2015 and did not notice our news.

The reboot of our project with a proper marketing campaign seemed to be the only way to get noticed by more players. And the campaign is working out good so far.

We had long talks with the latest active players and they aggreed with us that the best way to populate our server again, is to restart it at some point with more marketing beforehand. We are also sorry, that you missed this discussion due to your inactivity.
